name: 'Get Latest Tag Based'
description: 'Get the latest tag from git and outputs that for use in other actions'
branding:
  icon: 'tag'
  color: 'gray-dark'
outputs:
  tag:
    description: 'Latest tag'
runs:
  using: 'node12'
  main: 'main.js'
